### ISSUE TITLE
Compiling on MacOS

### ISSUE THREAD

**Issue by ORESoftware** [izabera/waiter#2]
I saw this answer on SO:
https://stackoverflow.com/a/39231660/1223975

I am trying to listen for when **any** given pid dies...

I tried compiling `waiter.c` by itself, I get these errors:

```
$ gcc src/waiter.c 

In file included from src/waiter.c:2:
/usr/include/sys/ptrace.h:99:26: error: unknown type name 'pid_t'
int     ptrace(int _request, pid_t _pid, caddr_t _addr, int _data);
                             ^
/usr/include/sys/ptrace.h:99:38: error: unknown type name 'caddr_t'
int     ptrace(int _request, pid_t _pid, caddr_t _addr, int _data);
                                         ^
src/waiter.c:10:14: error: use of undeclared identifier 'PTRACE_SEIZE'
  if (ptrace(PTRACE_SEIZE, pid, NULL, NULL) == -1) return 1;
             ^
3 errors generated.
```

maybe it's because I am on a Mac?

**Comment by ORESoftware** [comment]
When I clone the project and run `make` from the project root on a Mac, I get this:

```console
$ make
uname -rs | awk -F'[ .]' '$1 != "Linux" || $2 < 3 || ($2 == 3 && $3 < 4) { exit 1 }'
make: *** [waiter] Error 1
```

**Comment by izabera** [comment]
pm-tools is linux specific

waiter isn't terribly complex and it can probably be implemented with ptrace on a mac

but i don't know enough of how macs work and i can't help you

**Comment by ORESoftware** [comment]
@izabera  yeah np, I guess my main question is - what is the `ptrace()` call meant to do in the waiter.c file? in other words, why is `waitid()` not sufficient?

**Comment by izabera** [comment]
because you can only wait on direct children normally

**Comment by ORESoftware** [comment]
yes that makes sense, so `ptrace()` is used to wait on any pid? then why do you need `waitid()`?

**Comment by ORESoftware** [comment]
For my use case, I don't need `waitid()`, since I know I am trying to hook into a non-child-process.
I just need to figure out how to get `ptrace()` to work on OSX now.

**Comment by brainopener** [comment]
@ORESoftware 
Looks to me for MacOS and from a console app, you'll need to use kqueues:
https://developer.apple.com/library/content/technotes/tn2050/_index.html

**Comment by ORESoftware** [comment]
thanks @brainopener that looks like the right kind of info

**Comment by brainopener** [comment]
@ORESoftware 
Check this out:
https://github.com/brainopener/mac-pid-waiter

**Comment by ORESoftware** [comment]
@brainopener thanks, that has the right behavior, I got it to compile and ran it

how does it work? Does it avoid polling somehow? On linux, I am using this:

```bash
  tail --pid=${pid} -f /dev/null
```

but I read about `tail` and that uses polling in that case, lol

**Comment by brainopener** [comment]
@ORESoftware 
It's registering with kqueue to receive [NOTE_EXIT](https://www.freebsd.org/cgi/man.cgi?kqueue) events (that's the first kevent call) on that pid.

The next kevent call should block until NOTE_EXIT occurs. I was seeing online that everyone wraps kevent calls in a loop and so I did the same. I get the impression that maybe kevent returns in rare circumstances and needs the userland caller to call back into it (kind of like how a select call on a listening socket can do that occasionally).

You could remove the loop to verify.

**Comment by ORESoftware** [comment]
Got it, that's awesome. Works for me. I need to support Linux as well. Any idea of a good way to implement something similar for Linux? (I believe `waitid()`, `waitpid()`, and `wait()` all use polling, using `kill` under the hood.)

**Comment by brainopener** [comment]
@ORESoftware 
This pm-tools project you're commenting on works well for Linux. I use it in a deployment script (which is why I watch the repo).

**Comment by ORESoftware** [comment]
@brainopener yes, sorry, but I updated my comment - I believe `waitid()`, `waitpid()`, and `wait()` all use polling, using `kill` under the hood, pm-tools is using those.

**Comment by brainopener** [comment]
@ORESoftware 
waitpid waits on a SIGCHLD signal to show up when the "child" (now child process because of that ptrace stuff before) terminates. That's not polled -- it's the usual Linux signal passing mechanism.

**Comment by ORESoftware** [comment]
Yeah...on MacOS, `waitpid() / waitid()` only seems to work for a child process, but maybe on Linux it can work for any process?

**Comment by brainopener** [comment]
@ORESoftware 
waitpid on Linux works the same --- it only works for a child process.

That ptrace call with PTRACE_SEIZE flag changes the ownership of the target process. So, now waiter is the parent of the target pid.

On Mac, there's no PTRACE_SEIZE flag. And the closest thing I could find (PTRACE_ADD, I think?) didn't "just work" as a regular user.

Thus, the kqueue method over on that platform.

**Comment by ORESoftware** [comment]
@brainopener right..the code in this lib's waiter.c file is:

 ```c
return waitid(P_PID, pid, &sig, WEXITED|WNOWAIT);
```

I think `waitid()`, like `waitpid()` only works for child processes, so that's why I need something else

**Comment by brainopener** [comment]
@ORESoftware 
Do you see the ptrace call before it? That makes waitid work for that pid by "seizing" it (just like a debugger would do).

**Comment by ORESoftware** [comment]
Yes, I just remembered that you mentioned that, my bad, thanks a ton for your help, I will use it

**Comment by ORESoftware** [comment]
@brainopener  your BSD/Darwin C file works, but waiter.c in this project is not working the same way. Here is my video demoing the problem:

https://www.useloom.com/share/d820552f531142ceaf3bb9f2c6e82ff2

**Comment by izabera** [comment]
try `sudo setcap cap_sys_ptrace+ep waiter`

**Comment by ORESoftware** [comment]
crap...trying to avoid `sudo`, but I will see if that works

**Comment by ORESoftware** [comment]
@izabera thanks that seemed to work, what does that setcap command do? anyway to avoid using sudo?

**Comment by ORESoftware** [comment]
probably want to put that in the README? or in a comment in the waiter.c file

**Comment by izabera** [comment]
setcap is needed to add the cap_sys_ptrace capability

that command is in the makefile

the readme says

>- Requires linux >= 3.4
>- Works by attaching with `ptrace(PTRACE_SEIZE, ...)`, which still requires `CAP_SYS_PTRACE`, but unlike `PTRACE_SEIZE` it can't be prevented by `prctl(PR_SET_DUMPABLE, 0, ...)`
